### ISSUE TITLE
Imgui error

### ISSUE THREAD

**Issue by NewGuy2k2** [StOneRPC/ETS2Trainer#3]
Hey, I've tried fixing this myself but I cant figure out how, I've got the latest sig for you : 48 8b 05 ? ? ? ? 48 8b 48 ? 80 79 I'm getting the Imgui error since the latest ETS2 update, Can you see if you also get this error please. 

![ets1](https://user-images.githubusercontent.com/26898259/164334542-f7cb8fc7-0efb-427f-8c1f-c1503297d67d.png)

**Comment by SloanPC** [comment]
Hey, I'm on the latest version of ETS2 and the current sig in the repo is still valid, is there any particular reason you had to change it? However the sig you are using should also work. As for the imgui error that is unrelated, are you sure you are using directx11 when launching the game? 
`ImGui::CreateContext()` is called on the first iterator of the present hook so you shouldn't be getting that error if you have complied it correctly and are on dx11.

**Comment by NewGuy2k2** [comment]
I had to change it as the current sig in the repo would inject but wouldn't do anything as is set anything, When I changed the sig to the one I'm using it worked, but I recently got a 1.3Gb ETS2 today and since then just get that error, I'll try re compiling and launch in direct x 11.
